# Numpy : Numerical python

In [2]:
import numpy as np

### Creating numpy array

- #### By python list
- 1D

In [9]:
li = [1,2,3,4,5]
array1D = np.array(li)
array1D

array([1, 2, 3, 4, 5])

- 2D

In [12]:
array2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2D 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

- #### By Built in functions



- np.ones((3, 4)) : Create an array of order 3 by 4 filled with ones.
- np.zeros((3, 4)) : Create an array of order 3 by 4 filled with zeros.
- np.empty((3, 4)) : Create an uninitialized array of order 3 by 4.
- np.full((3, 4), 7) : Create an array of order 3 by 4 filled with 7s.
- np.eye(3)` : Create a 3x3 identity matrix.
- np.diag([1, 2, 3, 4]) : Create a diagonal matrix with given values.
- np.random.rand(3, 4) : Create an array of order 3 by 4 with random values between 0 and 1.  
- np.random.randint(1, 10, (3, 4)) : Create an array of order 3 by 4 with random integers between 1 and 9.
- np.arange(1, 13).reshape(3, 4) : Create an array of order 3 by 4 with numbers from 1 to 12.  
- np.linspace(1, 10, 12).reshape(3, 4) : Create an array of order 3 by 4 with 12 evenly spaced numbers between 1 and 10.


In [15]:
arr = np.ones((3,4),dtype = int)
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [16]:
arr = np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
arr = np.empty((2,2))
arr

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 7.78829961e-312]])

In [18]:
arr = np.full((3,3),7)
arr

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [20]:
arr = np.eye(3,dtype = int)
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [45]:
#same use case as eye()
arr = np.identity(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
arr = np.diag([2,3,4])
arr

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [25]:
arr = np.random.rand(2,1)
arr

array([[0.37831734],
       [0.57240637]])

In [28]:
arr = np.random.randint(1,15,(3,3))
arr

array([[ 9,  4, 14],
       [ 7,  7,  9],
       [ 4,  9,  1]], dtype=int32)

In [34]:
arr = np.arange(1,11,3) # 3 is step means it return every third element considering 1 starting element.
arr

array([ 1,  4,  7, 10])

In [41]:
arr = np.arange(1,11,3).reshape(2,2) # Just reshaping or transforming previous array in 2D
arr

array([[ 1,  4],
       [ 7, 10]])

In [46]:
arr = np.linspace(1,10,7)
arr

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

- np.tile(array,(row-repeat,column-repeat)) : repeat row and column specififed number of times

In [48]:
arr = [[1,2],[3,4]]
tiled = np.tile(arr,(2,3))
tiled

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

### Array Attributes
- These provides additional information about ndarrays

In [53]:
arr = np.array([[1,2],[4,5],[7,8]])
arr

array([[1, 2],
       [4, 5],
       [7, 8]])

In [54]:
# ndim : returns the no of dimensions of an array
arr.ndim

2

In [55]:
# size : returns no of total elements in the array
arr.size

6

In [56]:
# dtype : returns the data type of an array
arr.dtype

dtype('int64')

In [57]:
# shape : returns the order of the array (no of rows , no of columns)
arr.shape

(3, 2)

In [58]:
# we can also change shape without using reshape function by this attribute
arr.shape = (2,3)
arr

array([[1, 2, 4],
       [5, 7, 8]])

### Arithematic operations on  Arrays

#### We can perform several arithematic operations between numpy arrays using both arithematic operator ( + , - , / , * ) and numpy built in functions

##### Some operations are given below

In [6]:
arr1 = np.array([[2,1],[4,2],[7,3]])
arr2 = np.array([[2,4],[1,5],[3,8]])
addition = np.add(arr1,arr2)
print("Addition : ")
addition

Addition : 


array([[ 4,  5],
       [ 5,  7],
       [10, 11]])

In [7]:
arr1 = np.array([[2,1],[4,2],[7,3]])
arr2 = np.array([[2,4],[1,5],[3,8]])
subtract = np.subtract(arr1,arr2)
print("Subtraction : ")
subtract

Subtraction : 


array([[ 0, -3],
       [ 3, -3],
       [ 4, -5]])

In [8]:
arr1 = np.array([[2,1],[4,2],[7,3]])
arr2 = np.array([[2,4],[1,5],[3,8]])
mul = np.multiply(arr1,arr2)
print("Multiplication : ")
mul

Multiplication : 


array([[ 4,  4],
       [ 4, 10],
       [21, 24]])

In [12]:
arr1 = np.array([[2,1],[4,2],[7,3]])
arr2 = np.array([[2,4],[1,5],[3,8]])
div = np.divide(arr1,arr2)  # arr1/arr2
print("Division : ")
div

Division : 


array([[1.        , 0.25      ],
       [4.        , 0.4       ],
       [2.33333333, 0.375     ]])

In [11]:
arr1 = np.array([[2,1],[4,2],[7,3]])
arr2 = np.array([[2,4],[1,5],[3,8]])
power = np.power(arr1,arr2) # arr1 = base and arr2 = power
print("Power : ")
power

Power : 


array([[   4,    1],
       [   4,   32],
       [ 343, 6561]])

In [13]:
arr1 = np.array([[2,1],[4,2],[7,3]])
arr2 = np.array([[2,4],[1,5],[3,8]])
modulus = np.mod(arr1,arr2)
print("Remainder : ")
modulus

Remainder : 


array([[0, 1],
       [0, 2],
       [1, 3]])

In [15]:
arr1 = np.array([[2,1],[4,2],[7,3]])
sqrt = np.sqrt(arr1)
print("Square Root : ")
sqrt

Square Root : 


array([[1.41421356, 1.        ],
       [2.        , 1.41421356],
       [2.64575131, 1.73205081]])

In [18]:
arr1 = np.array([[2,1],[4,2],[7,3]])
reci = np.reciprocal(arr1)
print("Reciprocal : ")
reci

Reciprocal : 


array([[0, 1],
       [0, 0],
       [0, 0]])

In [22]:
angles = np.array( [90,0.5])
arr = np.cos(angles)
arr

array([-0.44807362,  0.87758256])

### Maximum and Minimum

In [29]:
arr = np.array([[2,1,3],[9,5,6]])
max = np.max(arr)
print(max)

9


In [28]:
arr = np.array([[2,1,3],[9,5,6]])
min = np.min(arr)
print(min)

1


- We can also pass a key-pair arguement 'axis' in min and max function.
- When axis = 0. we are finding max or min element of each column.
- When axis = 1. we are finding max or min element of each row.

##### Maximum in columns

In [31]:
arr = np.array([[2,14,3],[9,5,6]])
max = np.max(arr,axis=0)
print(arr,'\n')
print(max)

[[ 2 14  3]
 [ 9  5  6]] 

[ 9 14  6]


##### Minimum in columns

In [32]:
arr = np.array([[2,14,3],[9,5,6]])
min = np.min(arr,axis=0)
print(arr,'\n')
print(min)

[[ 2 14  3]
 [ 9  5  6]] 

[2 5 3]


##### Maximum in rows

In [33]:
arr = np.array([[2,14,3],[9,5,6]])
max = np.max(arr,axis=1)
print(arr,'\n')
print(max)

[[ 2 14  3]
 [ 9  5  6]] 

[14  9]


##### Minimum in rows

In [34]:
arr = np.array([[2,14,3],[9,5,6]])
min = np.min(arr,axis=1)
print(arr,'\n')
print(min)

[[ 2 14  3]
 [ 9  5  6]] 

[2 5]


- ##### There are two more functions argmax() and argmin(). These works exactly same as max() and min() but returns the index of searched <br> maximum and minimum elements.


### Broadcasting in numpy arrays
#### Broadcasting in NumPy refers to the ability to perform element-wise operations on arrays of different shapes, by automatically expanding the smaller array to match the shape of the larger array. This is done without actually creating copies of the data, making it very memory efficient.

##### Rules : 
- Dimensions Compatibility: The dimensions of the arrays being operated on must either be the same, or one of them must be 1.
- Size Compatibility: The size of the dimensions must be either the same or one of them must be 1.

#### 1. Broadcasting a Scalar to an Array
A scalar value is broadcasted across all elements of an array. NumPy automatically expands the scalar to match the shape of the array.


In [36]:
arr = np.array([1, 2, 3, 4, 5])
scalar = 10

result = arr + scalar  # Scalar is broadcasted to match the shape of arr

print(result) 

[11 12 13 14 15]


#### 2. Broadcasting a 1D Array to a 2D Array
A (1, n) array is broadcasted to an (m, n) array. Here, arr_1d is added to each row of arr_2d.

In [37]:
import numpy as np

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2,3)
arr_1d = np.array([10, 20, 30])  # Shape (3,)

result = arr_2d + arr_1d  # arr_1d is broadcasted along rows

print(result)

[[11 22 33]
 [14 25 36]]


#### 3. Broadcasting a Column Vector to a 2D Matrix
A (m,1) array is broadcasted to an (m,n) array, meaning that the single column vector gets expanded across columns.

In [38]:
import numpy as np

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2,3)
column_vector = np.array([[10], [20]])  # Shape (2,1)

result = arr_2d + column_vector  # column_vector is broadcasted across columns

print(result)

[[11 12 13]
 [24 25 26]]


#### 4. Broadcasting Different Shapes (1D and 2D)
Broadcasting happens when dimensions differ but are compatible. In this case, a row vector (arr_1d) is broadcasted across each <br> row of a column vector (arr_2d).

In [40]:
arr_1d = np.array([1, 2, 3])  # Shape (3,)
arr_2d = np.array([[10], [20], [30]])  # Shape (3,1)

result = arr_1d + arr_2d  # arr_1d is broadcasted along columns

print(result)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


### Indexing and Slicing
Indexing and slicing works same as string and list in numpy arrays.

- arr [row-start : row-end : row-step , column-start : column-end : column-step]

In [3]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [67]:
arr[1:3] # second and third row

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [66]:
arr[1::2] # every second row from 2nd row

array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20]])

In [65]:
arr[::2] # every second row from 1st row

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [64]:
arr[:2] # first two rows

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [63]:
arr[:,:2] # first two columns

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17]])

In [4]:
arr[1:3,2:] 

array([[ 8,  9, 10],
       [13, 14, 15]])

In [62]:
arr[::2,2:]

array([[ 3,  4,  5],
       [13, 14, 15]])

In [6]:
arr[:2,:2] # first two rows and columns

array([[1, 2],
       [6, 7]])

### Iteration over a numpy array

In [7]:
# Creating a 3D NumPy array (2x3x4)
array_3d = np.array([
    [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], 
    [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]
])

print(array_3d)
print("Shape:", array_3d.shape)  # Output: (2, 3, 4)


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)


- Poor approach and become difficult for the arrays having more no of dimensions.

In [12]:
for i in array_3d:
    for j in i:
        for k in j:
            print(k)

- Built in function in numpy for iterating an array.

In [9]:
for ele in np.nditer(array_3d):
    print(ele)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


In [16]:
for index,ele in np.ndenumerate(array_3d):
    print('Index :',index,'Element : ',ele)

Index : (0, 0, 0) Element :  1
Index : (0, 0, 1) Element :  2
Index : (0, 0, 2) Element :  3
Index : (0, 0, 3) Element :  4
Index : (0, 1, 0) Element :  5
Index : (0, 1, 1) Element :  6
Index : (0, 1, 2) Element :  7
Index : (0, 1, 3) Element :  8
Index : (0, 2, 0) Element :  9
Index : (0, 2, 1) Element :  10
Index : (0, 2, 2) Element :  11
Index : (0, 2, 3) Element :  12
Index : (1, 0, 0) Element :  13
Index : (1, 0, 1) Element :  14
Index : (1, 0, 2) Element :  15
Index : (1, 0, 3) Element :  16
Index : (1, 1, 0) Element :  17
Index : (1, 1, 1) Element :  18
Index : (1, 1, 2) Element :  19
Index : (1, 1, 3) Element :  20
Index : (1, 2, 0) Element :  21
Index : (1, 2, 1) Element :  22
Index : (1, 2, 2) Element :  23
Index : (1, 2, 3) Element :  24


### Joining and Spliting

In [19]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

In [22]:
result = np.concatenate((arr1,arr2)) # By default axis equals to 0 (row)
result

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [24]:
result = np.concatenate((arr1,arr2),axis =1)
result

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [31]:
splitted = np.array_split(arr1,2)
splitted

[array([[1, 2, 3]]), array([[4, 5, 6]])]

### Searching in numpy array

#### Where():
How It Works Internally
The where() function:

Creates a boolean mask from the given condition.
Finds the indices where the condition is True (if only the condition is given).
Selects elements from x (if the condition is True) or from y (if the condition is False).

In [34]:
arr = np.array([2,5,1,8,9,3,11,17,23,12,21,16,22])
even = np.where(arr % 2 == 0) # Find indices of even numbers
even

(array([ 0,  3,  9, 11, 12]),)

In [35]:
modified_arr = np.where(arr < 10, 0, arr)

print(modified_arr)

[ 0  0  0  0  0  0 11 17 23 12 21 16 22]


In [37]:
result = np.where((arr >= 5) & (arr <= 10))

print(arr[result])  # Output: [5 8 9 11 17 12 16]


[5 8 9]


In [40]:
labels = np.where(arr % 2 == 0, "EVEN", "ODD")

print(labels)

['EVEN' 'ODD' 'ODD' 'EVEN' 'ODD' 'ODD' 'ODD' 'ODD' 'ODD' 'EVEN' 'ODD'
 'EVEN' 'EVEN']
